/* global window */
// Mock data for Instaagent inbox prototype

const accent = (deg, sat = 0.13) => `oklch(60% ${sat} ${deg})`;

const AVATARS = {
  madina: { color: 'linear-gradient(135deg,#e8a07a,#c75d3f)', initials: 'MK' },
  dmitry: { color: 'linear-gradient(135deg,#7fa8d1,#3a6aa3)', initials: 'ДС' },
  sarah:  { color: 'linear-gradient(135deg,#d6b48a,#a07a4a)', initials: 'SL' },
  aziza:  { color: 'linear-gradient(135deg,#d97b8a,#9b3f5a)', initials: 'AT' },
  bakhrom:{ color: 'linear-gradient(135deg,#a8b899,#5d7548)', initials: 'БС' },
  ella:   { color: 'linear-gradient(135deg,#cfa8d6,#7e4f9b)', initials: 'EB' },
  shox:   { color: 'linear-gradient(135deg,#e3c87a,#a07e2a)', initials: 'SH' },
  nightowl:{color: 'linear-gradient(135deg,#7a8aa8,#3f4f6f)', initials: 'NO' },
  ruslan: { color: 'linear-gradient(135deg,#c9a07f,#7a5238)', initials: 'РБ' },
  feruza: { color: 'linear-gradient(135deg,#e8b09f,#b46449)', initials: 'FN' },
  hassan: { color: 'linear-gradient(135deg,#9bc4a8,#3f7d5e)', initials: 'HA' },
  laylo:  { color: 'linear-gradient(135deg,#c7b598,#7d6643)', initials: 'LR' },
  amir:   { color: 'linear-gradient(135deg,#a8c4d6,#4a7088)', initials: 'AM' },
};

window.CONVERSATIONS = [
  {
    id: 'c1',
    name: 'Madina Karimova',
    handle: '@madina.k_',
    platform: 'instagram',
    avatar: AVATARS.madina,
    lang: 'uz',
    online: true,
    needsHuman: true,
    aiOn: false,
    unread: 0,
    lastTime: '2 min',
    lastAt: 'today',
    lastFromMe: false,
    preview: 'Iltimos, sariq sumkani 36-o\u02bclchamda zaxiraga olib qo\u02bbysangiz...',
    tags: ['VIP', 'Returning'],
    customerSince: 'March 2025',
    location: 'Tashkent, UZ',
    summary: 'Wants to reserve the mustard tote in size 36 and pay on delivery. Asked twice if it\u2019s in stock \u2014 needs a human confirm.',
    kpis: { orders: 4, ltv: '1,420', last: '12d', conv: '+18%' },
    orders: [
      { t: 'Linen tote — Sand', s: 'Aug 2025 · Delivered', price: '$78' },
      { t: 'Crossbody — Olive', s: 'May 2025 · Delivered', price: '$94' },
    ],
    suggestions: [
      'Ha, sariq sumka mavjud — yetkazib berish 2 kun.',
      'Iltimos, manzilingizni yuboring 📍',
      'Kechirasiz, hozir manager bog\u02bblanadi.',
    ],
  },
  {
    id: 'c2',
    name: 'Дмитрий Соколов',
    handle: '@d.sokolov',
    platform: 'telegram',
    avatar: AVATARS.dmitry,
    lang: 'ru',
    online: false,
    needsHuman: true,
    aiOn: false,
    unread: 2,
    lastTime: '14 min',
    lastFromMe: false,
    preview: 'Можно ли вернуть товар если кожа треснула после месяца?',
    tags: ['Complaint'],
    summary: 'Leather on his wallet cracked after a month. Wants a return or replacement. AI handed off after detecting frustration.',
    customerSince: 'Jan 2026',
    location: 'Almaty, KZ',
    kpis: { orders: 1, ltv: '64', last: '32d', conv: '—' },
    orders: [
      { t: 'Bifold wallet — Cognac', s: 'Apr 2026 · Delivered', price: '$64' },
    ],
    suggestions: [
      'Конечно, мы заменим бесплатно.',
      'Пришлите фото, пожалуйста.',
      'Спасибо, передам менеджеру.',
    ],
  },
  {
    id: 'c3',
    name: 'Sarah Lin',
    handle: '@sarahleather',
    platform: 'instagram',
    avatar: AVATARS.sarah,
    lang: 'en',
    online: true,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '1 hr',
    lastFromMe: true,
    preview: 'Sent catalog · "Browse the spring drop here →"',
    tags: ['Lead'],
    summary: 'Discovered the brand via Reels. Browsing the spring catalog right now.',
    customerSince: 'today',
    location: 'Berlin, DE',
    kpis: { orders: 0, ltv: '0', last: '—', conv: 'new' },
    orders: [],
    suggestions: [
      'Anything caught your eye?',
      'Free shipping over $120 ✨',
      'Want our size guide?',
    ],
  },
  {
    id: 'c4',
    name: 'Aziza Toshmatova',
    handle: '@aziza.tosh',
    platform: 'instagram',
    avatar: AVATARS.aziza,
    lang: 'uz',
    online: false,
    needsHuman: true,
    aiOn: false,
    unread: 1,
    lastTime: '3 hr',
    lastFromMe: false,
    preview: 'To\u02bblovni o\u02bbtkazdim, chek yuboryapman 💳',
    tags: ['Paying'],
    summary: 'Sent a payment receipt for $156. Needs human to confirm the transfer landed and dispatch the order.',
    customerSince: 'Feb 2025',
    location: 'Samarkand, UZ',
    kpis: { orders: 6, ltv: '780', last: '8d', conv: '+12%' },
    orders: [
      { t: 'Mini bag — Camel', s: 'Pending payment', price: '$156' },
    ],
    suggestions: [
      'Rahmat, to\u02bblovni tasdiqlaymiz 🙏',
      'Bir necha daqiqada javob beramiz.',
    ],
  },
  {
    id: 'c5',
    name: 'Бахром Саидов',
    handle: '@bakhrom_s',
    platform: 'telegram',
    avatar: AVATARS.bakhrom,
    lang: 'ru',
    online: true,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '5 hr',
    lastFromMe: true,
    preview: 'AI: «Доставка в Ташкент 1-2 дня, оплата при получении.»',
    tags: ['Returning'],
    summary: 'Returning customer asking about delivery time to Tashkent. AI answered.',
    customerSince: 'Sep 2024',
    location: 'Tashkent, UZ',
    kpis: { orders: 3, ltv: '342', last: '21d', conv: '+8%' },
    orders: [
      { t: 'Leather belt — Black', s: 'Oct 2025 · Delivered', price: '$48' },
    ],
    suggestions: [],
  },
  {
    id: 'c6',
    name: 'Ella Boutique',
    handle: '@ellaboutique',
    platform: 'instagram',
    avatar: AVATARS.ella,
    lang: 'en',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '8 hr',
    lastFromMe: false,
    preview: 'Hi! Would love to talk about a wholesale partnership 🤝',
    tags: ['Wholesale'],
    summary: 'Reaching out about wholesale.',
    customerSince: 'today',
    location: 'Tbilisi, GE',
    kpis: { orders: 0, ltv: '0', last: '—', conv: 'new' },
    orders: [],
    suggestions: [],
  },
  {
    id: 'c7',
    name: 'Shoxruh Yusupov',
    handle: '@shox_y',
    platform: 'telegram',
    avatar: AVATARS.shox,
    lang: 'uz',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 1,
    lastTime: 'yesterday',
    lastFromMe: false,
    preview: '🎤 Voice message · 0:18',
    tags: [],
    summary: 'Sent a voice asking about belt sizes.',
    customerSince: 'Jul 2025',
    location: 'Bukhara, UZ',
    kpis: { orders: 2, ltv: '120', last: '40d', conv: '—' },
    orders: [],
    suggestions: [],
  },
  {
    id: 'c8',
    name: 'nightowl_22',
    handle: '@nightowl_22',
    platform: 'instagram',
    avatar: AVATARS.nightowl,
    lang: 'en',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: 'yesterday',
    lastFromMe: true,
    preview: 'AI: "We ship worldwide \u2014 EU usually 5-7 days."',
    tags: [],
    summary: 'Asked about international shipping. AI answered.',
    customerSince: 'today',
    location: 'Toronto, CA',
    kpis: { orders: 0, ltv: '0', last: '—', conv: 'new' },
    orders: [],
    suggestions: [],
  },
  {
    id: 'c9',
    name: 'Руслан Б.',
    handle: '@ruslan.b',
    platform: 'telegram',
    avatar: AVATARS.ruslan,
    lang: 'ru',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '2 days',
    lastFromMe: false,
    preview: 'Спасибо, заказ получил 👍',
    tags: ['Returning'],
    summary: 'Confirmed receiving his order. Happy customer.',
    customerSince: 'Mar 2025',
    location: 'Astana, KZ',
    kpis: { orders: 5, ltv: '512', last: '2d', conv: '+22%' },
    orders: [],
    suggestions: [],
  },
  {
    id: 'c10',
    name: 'Feruza N.',
    handle: '@feruza.n',
    platform: 'instagram',
    avatar: AVATARS.feruza,
    lang: 'uz',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '3 days',
    lastFromMe: true,
    preview: 'AI: "Katalog: button orqali ko\u02bbring 🌿"',
    tags: [],
    summary: 'Asked for catalog, AI sent the button.',
    customerSince: 'Jun 2025',
    location: 'Andijan, UZ',
    kpis: { orders: 1, ltv: '62', last: '90d', conv: '—' },
    orders: [],
    suggestions: [],
  },
  // --- WhatsApp ---
  {
    id: 'w1',
    name: 'Hassan Aliyev',
    handle: '+998 90 123 45 67',
    platform: 'whatsapp',
    avatar: AVATARS.hassan,
    lang: 'uz',
    online: true,
    needsHuman: true,
    aiOn: false,
    unread: 3,
    lastTime: '6 min',
    lastFromMe: false,
    preview: 'Salom, kecha buyurtma qildim, lekin chek kelmadi. Tekshira olasizmi?',
    tags: ['Paying', 'Urgent'],
    summary: 'Ordered last night but the receipt didn\u2019t arrive. Sounds nervous \u2014 take over and verify the payment.',
    customerSince: 'May 2025',
    location: 'Tashkent, UZ',
    kpis: { orders: 2, ltv: '218', last: '1d', conv: '+4%' },
    orders: [
      { t: 'Crossbody — Cognac', s: 'Pending dispatch', price: '$118' },
    ],
    suggestions: [
      'Salom Hassan, tekshiryapman \u2014 bir daqiqa 🙏',
      'Buyurtma topildi, hozir chek yuboraman.',
      'Iltimos, to\u02bblov vaqtini ayting.',
    ],
  },
  {
    id: 'w2',
    name: 'Laylo Rakhimova',
    handle: '+998 99 887 65 43',
    platform: 'whatsapp',
    avatar: AVATARS.laylo,
    lang: 'uz',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 1,
    lastTime: '40 min',
    lastFromMe: false,
    preview: '🎤 Voice message \u00b7 0:24',
    tags: ['Lead'],
    summary: 'Sent a voice note asking about gift wrapping. AI is preparing a reply.',
    customerSince: 'today',
    location: 'Fergana, UZ',
    kpis: { orders: 0, ltv: '0', last: '—', conv: 'new' },
    orders: [],
    suggestions: [
      'Albatta, sovg\u02bba qog\u02bbozi bepul 🎁',
      'Kechirasiz, qaysi mahsulot kerak?',
    ],
  },
  {
    id: 'w3',
    name: 'Amir Husain',
    handle: '+971 50 412 88 30',
    platform: 'whatsapp',
    avatar: AVATARS.amir,
    lang: 'en',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '4 hr',
    lastFromMe: true,
    preview: 'AI: "Shipping to Dubai is 4-6 days, $18 flat."',
    tags: ['International'],
    summary: 'Asked about shipping to Dubai. AI answered.',
    customerSince: 'Mar 2026',
    location: 'Dubai, AE',
    kpis: { orders: 1, ltv: '142', last: '14d', conv: '+6%' },
    orders: [
      { t: 'Card holder — Tan', s: 'Apr 2026 · Delivered', price: '$42' },
    ],
    suggestions: [],
  },
];

// Thread messages for the active (default) conversation = c1
window.THREADS = {
  c1: [
    { id: 'm1', day: 'Yesterday', side: 'inbound',  type: 'text', time: '14:02', text: 'Salom! Sumkalaringizni Reels da ko\u02bbrdim, juda chiroyli 🤎' },
    { id: 'm2', side: 'outbound', from: 'ai',   type: 'text', time: '14:02', text: 'Salom, Madina! Rahmat 🤍 Sizga qaysi rang qiziq?' },
    { id: 'm3', side: 'inbound',  type: 'text', time: '14:05', text: 'Sariq yoki sarg\u02bbish kremga. Modellaringiz ko\u02bbpmi?' },
    { id: 'm4', side: 'outbound', from: 'ai',   type: 'catalog', time: '14:05',
      catalogText: 'Albatta 😊 Hozirgi kolleksiyani quyidagi tugma orqali ko\u02bbrishingiz mumkin.',
      catalogLabel: 'Katalogni ko\u02bbrish' },
    { id: 'm5', day: 'Today', side: 'inbound', type: 'text', time: '11:14', text: 'Sariq sumka chiroyli ekan! 36-o\u02bblcham bormi?' },
    { id: 'm6', side: 'outbound', from: 'ai', type: 'text', time: '11:14',
      text: 'Sariq tote 36-o\u02bblchamda bor 🌼 Yetkazib berish 1-2 ish kuni.' },
    { id: 'm7', side: 'inbound', type: 'media', time: '11:18',
      label: 'IG attachment · 1.2 MB', mediaCaption: 'Bu rangga o\u02bbxshashmi?' },
    { id: 'm8', side: 'inbound', type: 'text', time: '11:19',
      text: 'Iltimos, sariq sumkani 36-o\u02bblchamda zaxiraga olib qo\u02bbysangiz. To\u02bblovni yetkazib berishda qilaman.' },
    { id: 'handoff', side: 'system', type: 'handoff', time: '11:20',
      text: 'Madina is ready to buy and asking for a reservation. AI paused so you can confirm stock.' },
  ],
};

// Threads for other convos (lighter)
window.THREADS.c2 = [
  { id: 'd1', day: 'Today', side: 'inbound', type: 'text', time: '08:40', text: 'Здравствуйте. Кошелёк, который я купил месяц назад, треснул по шву.' },
  { id: 'd2', side: 'outbound', from: 'ai', type: 'text', time: '08:41', text: 'Здравствуйте, Дмитрий. Очень жаль это слышать 🙏 Менеджер свяжется в ближайшее время.' },
  { id: 'd3', side: 'inbound', type: 'media', time: '08:42', label: 'photo · cracked-seam.jpg', mediaCaption: 'Вот фото.' },
  { id: 'd4', side: 'inbound', type: 'text', time: '08:55', text: 'Можно ли вернуть товар если кожа треснула после месяца?' },
  { id: 'handoff', side: 'system', type: 'handoff', time: '08:55',
    text: 'Customer is asking about a return policy after a defect. Tone is frustrated. Take over.' },
];

window.THREADS.c3 = [
  { id: 's1', day: 'Today', side: 'inbound', type: 'text', time: '13:18', text: 'Hey! Just discovered you via Reels — your spring drop is gorgeous 🌷' },
  { id: 's2', side: 'outbound', from: 'ai', type: 'text', time: '13:18', text: 'Thank you, Sarah ✨ The spring drop is our favorite too. What kind of bag are you looking for?' },
  { id: 's3', side: 'inbound', type: 'text', time: '13:19', text: 'A small shoulder bag, ideally in something earthy.' },
  { id: 's4', side: 'outbound', from: 'ai', type: 'catalog', time: '13:19',
    catalogText: 'You\u2019ll love these earthy tones \u2014 here\u2019s the full lookbook:',
    catalogLabel: 'Browse the spring drop \u2192' },
];

window.THREADS.c7 = [
  { id: 'v1', day: 'Yesterday', side: 'inbound', type: 'voice', time: '19:41', duration: '0:18' },
  { id: 'v2', side: 'outbound', from: 'ai', type: 'text', time: '19:42',
    text: 'Salom! Voice xabaringiz qabul qilindi. Kamarlar 32 dan 44 gacha o\u02bblchamlarda mavjud 🌿' },
];

window.THREADS.w1 = [
  { id: 'h1', day: 'Yesterday', side: 'inbound', type: 'text', time: '22:11', text: 'Salom! Crossbody cognac sumkani buyurtma qilmoqchiman. Yetkazib berish Toshkent ichida bormi?' },
  { id: 'h2', side: 'outbound', from: 'ai', type: 'text', time: '22:12', text: 'Salom Hassan! Albatta, Toshkent ichida 1-2 ish kuni 🌿 Manzilingizni yuborsangiz, hisob-faktura tayyorlayman.' },
  { id: 'h3', side: 'inbound', type: 'text', time: '22:30', text: 'Mirzo Ulug\u02bbbek tumani, Buyuk Ipak Yo\u02bbli ko\u02bbchasi 12.' },
  { id: 'h4', side: 'outbound', from: 'ai', type: 'text', time: '22:31', text: 'Rahmat 🙌 Buyurtma summasi $118. Karta orqali to\u02bblovni yuboring \u2014 raqamni jo\u02bbnataman.' },
  { id: 'h5', side: 'inbound', type: 'media', time: '23:04', label: 'photo · payment-receipt.jpg', mediaCaption: 'To\u02bblov o\u02bbtdi 🙏' },
  { id: 'h6', day: 'Today', side: 'inbound', type: 'text', time: '09:15', text: 'Salom, kecha buyurtma qildim, lekin chek kelmadi. Tekshira olasizmi?' },
  { id: 'h7', side: 'inbound', type: 'text', time: '09:16', text: 'Pul yechib olindi, lekin SMS kelmadi 😟' },
  { id: 'h8', side: 'inbound', type: 'text', time: '09:18', text: 'Iltimos, tezroq javob bering.' },
  { id: 'handoff', side: 'system', type: 'handoff', time: '09:18', text: 'Payment landed yesterday at 23:04 but no receipt was sent. Hassan is anxious \u2014 confirm dispatch and apologize.' },
];

window.THREADS.w2 = [
  { id: 'l1', day: 'Today', side: 'inbound', type: 'text', time: '13:20', text: 'Assalomu alaykum 🌿' },
  { id: 'l2', side: 'inbound', type: 'voice', time: '13:20', duration: '0:24' },
  { id: 'l3', side: 'outbound', from: 'ai', type: 'text', time: '13:21', text: 'Vaalaykum assalom! Albatta, sovg\u02bba o\u02bbrash xizmatimiz bepul 🎁 Qaysi mahsulotni tanlamoqchisiz?' },
];

window.THREADS.w3 = [
  { id: 'a1', day: 'Today', side: 'inbound', type: 'text', time: '10:02', text: 'Hi! Do you ship to the UAE? Looking at the card holder.' },
  { id: 'a2', side: 'outbound', from: 'ai', type: 'text', time: '10:02', text: 'Hi Amir 👋 Yes, shipping to Dubai takes 4\u20136 working days, flat $18.' },
  { id: 'a3', side: 'inbound', type: 'text', time: '10:04', text: 'Perfect, I\u2019ll order tomorrow.' },
];

// Default
const DEFAULT_THREAD = [];
window.getThread = (id) => window.THREADS[id] || DEFAULT_THREAD;

// i18n strings (just for headings/labels — chat content stays as customer wrote it)
window.STRINGS = {
  en: {
    appName: 'Insta', appNameAccent: 'agent',
    inbox: 'Inbox', insights: 'Insights', knowledge: 'Knowledge', accounts: 'Accounts', settings: 'Settings',
    search: 'Search conversations…',
    all: 'All', needs: 'Needs you', unread: 'Unread', aiHandled: 'Handled by AI', closed: 'Closed',
    instagram: 'Instagram', telegram: 'Telegram', whatsapp: 'WhatsApp',
    priority: 'Priority', everything: 'Everything else',
    aiOn: 'AI replying', aiOff: 'You\u2019re replying',
    suggested: 'Suggested replies',
    typing: 'Reply to', kbdHint: 'Enter to send · Shift+Enter for newline',
    send: 'Send',
    about: 'About', summary: 'Summary', orders: 'Recent orders', stats: 'Lifetime', notes: 'Internal notes',
    note: 'Loves natural tones. Prefers cash on delivery. Birthday in October.',
    takeover: 'Take over chat', handoffTitle: 'Needs a human',
    aiResume: 'Let AI resume replying',
  },
  uz: {
    appName: 'Insta', appNameAccent: 'agent',
    inbox: 'Pochta', insights: 'Statistika', knowledge: 'Bilim', accounts: 'Akkauntlar', settings: 'Sozlash',
    search: 'Suhbatlar ichidan izlash\u2026',
    all: 'Hammasi', needs: 'Sizga kerak', unread: 'O\u02bbqilmagan', aiHandled: 'AI javob berdi', closed: 'Yopilgan',
    instagram: 'Instagram', telegram: 'Telegram', whatsapp: 'WhatsApp',
    priority: 'Muhim', everything: 'Boshqalar',
    aiOn: 'AI javob beryapti', aiOff: 'Siz javob beryapsiz',
    suggested: 'Tavsiya etilgan javoblar',
    typing: 'Javob', kbdHint: 'Enter — yuborish · Shift+Enter — yangi qator',
    send: 'Yuborish',
    about: 'Mijoz', summary: 'Xulosa', orders: 'Buyurtmalar', stats: 'Umumiy', notes: 'Eslatma',
    note: 'Tabiiy ranglarni yaxshi ko\u02bbradi. Yetkazib berishda to\u02bblaydi. Tug\u02bbilgan kuni \u2014 oktyabr.',
    takeover: 'Suhbatni o\u02bbz qo\u02bbliga olish', handoffTitle: 'Insonga muhtoj',
    aiResume: 'AI javob berishni davom ettirsin',
  },
  ru: {
    appName: 'Insta', appNameAccent: 'agent',
    inbox: 'Входящие', insights: 'Аналитика', knowledge: 'База знаний', accounts: 'Аккаунты', settings: 'Настройки',
    search: 'Поиск по диалогам\u2026',
    all: 'Все', needs: 'Нужны вы', unread: 'Непрочит.', aiHandled: 'ИИ ответил', closed: 'Закрыты',
    instagram: 'Instagram', telegram: 'Telegram', whatsapp: 'WhatsApp',
    priority: 'Приоритет', everything: 'Остальное',
    aiOn: 'ИИ отвечает', aiOff: 'Вы отвечаете',
    suggested: 'Подсказки ответа',
    typing: 'Ответ', kbdHint: 'Enter — отправить · Shift+Enter — новая строка',
    send: 'Отправить',
    about: 'Клиент', summary: 'Резюме', orders: 'Последние заказы', stats: 'За всё время', notes: 'Заметка',
    note: 'Любит природные оттенки. Платит при доставке. День рождения в октябре.',
    takeover: 'Взять диалог', handoffTitle: 'Нужен человек',
    aiResume: 'Передать обратно ИИ',
  },
};
