/* global window */

// Multilingual strings
window.STRINGS = {
  en: {
    appName: 'Insta',
    appNameAccent: 'agent',
    inbox: 'Inbox',
    insights: 'Insights',
    knowledge: 'Knowledge',
    accounts: 'Accounts',
    settings: 'Settings',
    search: 'Search conversations...',
    all: 'All',
    needs: 'Needs Human',
    unread: 'Unread',
    aiHandled: 'AI Handled',
    priority: 'Priority',
    everything: 'Everything',
    instagram: 'Instagram',
    telegram: 'Telegram',
    whatsapp: 'WhatsApp',
    suggested: 'Suggested',
    typing: 'Type to',
    send: 'Send',
    sending: 'Sending',
    kbdHint: 'Shift+Enter for new line',
    noConversation: 'Select a conversation to start',
    noMessages: 'No messages yet',
    loading: 'Loading...',
    handoffTitle: 'Conversation taken over',
    handoffMessage: 'A team member has taken over this conversation',
    summary: 'Summary',
    stats: 'Stats',
    orders: 'Orders',
    notes: 'Notes',
    note: 'Add notes about this customer',
  },
  uz: {
    appName: 'Insta',
    appNameAccent: 'agent',
    inbox: 'Inbox',
    insights: 'Tahlil',
    knowledge: 'Bilim',
    accounts: 'Akkauntlar',
    settings: 'Sozlamalar',
    search: 'Suhbatlarni qidiring...',
    all: 'Hammasi',
    needs: 'Odam Kerak',
    unread: 'O\'qilmagan',
    aiHandled: 'AI bilan',
    priority: 'Muhim',
    everything: 'Boshqa',
    instagram: 'Instagram',
    telegram: 'Telegram',
    whatsapp: 'WhatsApp',
    suggested: 'Tavsiyalangan',
    typing: 'Yozing',
    send: 'Yuborish',
    sending: 'Yuborilmoqda...',
    kbdHint: 'Shift+Enter yangi qator',
    noConversation: 'Suhbat tanlang',
    noMessages: 'Xabarlar yo\'q',
    loading: 'Yuklanmoqda...',
    handoffTitle: 'Suhbat o\'tkazildi',
    handoffMessage: 'Jamoaviy a\'zo bu suhbatni o\'z zimmasiga oldi',
    summary: 'Qisqacha',
    stats: 'Statistika',
    orders: 'Buyurtmalar',
    notes: 'Eslatmalar',
    note: 'Ushbu mijoz haqida eslatma qo\'shing',
  },
  ru: {
    appName: 'Insta',
    appNameAccent: 'agent',
    inbox: 'Входящие',
    insights: 'Аналитика',
    knowledge: 'Знания',
    accounts: 'Аккаунты',
    settings: 'Настройки',
    search: 'Поиск разговоров...',
    all: 'Все',
    needs: 'Нужен оператор',
    unread: 'Непрочитанные',
    aiHandled: 'ИИ обработал',
    priority: 'Приоритет',
    everything: 'Остальные',
    instagram: 'Instagram',
    telegram: 'Telegram',
    whatsapp: 'WhatsApp',
    suggested: 'Предложено',
    typing: 'Введите',
    send: 'Отправить',
    sending: 'Отправляется...',
    kbdHint: 'Shift+Enter для новой строки',
    noConversation: 'Выберите разговор',
    noMessages: 'Сообщений нет',
    loading: 'Загрузка...',
    handoffTitle: 'Разговор передан',
    handoffMessage: 'Член команды взял этот разговор на себя',
    summary: 'Краткая информация',
    stats: 'Статистика',
    orders: 'Заказы',
    notes: 'Заметки',
    note: 'Добавьте заметку об этом клиенте',
  },
};

// Mock conversation data (will be replaced by API)
window.CONVERSATIONS = [
  {
    id: 'instagram::biz1::dm::cust1',
    name: 'Malika Ahmed',
    handle: '@malika.fashion',
    platform: 'instagram',
    avatar: { initials: 'MA', color: 'linear-gradient(135deg,#e8a07a,#c75d3f)' },
    lang: 'uz',
    online: true,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: '2 min',
    lastFromMe: false,
    preview: 'Katalogni ko\'rish uchun link yuboring',
    lastAt: 'May 2025',
    tags: ['Returning', 'VIP'],
    customerSince: 'March 2025',
    location: 'Tashkent',
    summary: 'Regular customer. 47 messages. Last: catalog link request',
    kpis: { orders: 3, ltv: '450', last: '2 weeks', conv: '+15%' },
    orders: [
      { t: 'Pink dress XS', s: 'Delivered', price: '$89' },
      { t: 'Blue shoes', s: 'Pending', price: '$45' },
    ],
    suggestions: [
      'Katalogni ko\'ring: https://shop.example.com',
      'Qanday rang xohlaysiz?',
      'Sizga yangi kolleksiya yoq-xolos',
    ],
  },
  {
    id: 'instagram::biz1::dm::cust2',
    name: 'Adham Rashid',
    handle: '@adham.tech',
    platform: 'instagram',
    avatar: { initials: 'AR', color: 'linear-gradient(135deg,#7fa8d1,#3a6aa3)' },
    lang: 'uz',
    online: false,
    needsHuman: true,
    aiOn: false,
    unread: 3,
    lastTime: '45 min',
    lastFromMe: true,
    preview: 'Bulk order haqida savol',
    lastAt: 'May 2025',
    tags: ['Complaint', 'VIP'],
    customerSince: 'January 2025',
    location: 'Tashkent',
    summary: 'Bulk buyer. 120+ messages. Issue: Color mismatch on last order',
    kpis: { orders: 12, ltv: '2,400', last: '3 days', conv: '+42%' },
    orders: [
      { t: 'Bulk order (100x)', s: 'Processing', price: '$1,200' },
    ],
    suggestions: [
      'Kechirasiz, bu sotsiy meningiz?',
      'Rasm yuboringiz, tezda hal qilamiz',
      'Qaytarish jarayoni boshlangan',
    ],
  },
  {
    id: 'telegram::biz1::telegram::cust3',
    name: 'Fatima Uzbekova',
    handle: '@fatima_shop',
    platform: 'telegram',
    avatar: { initials: 'FU', color: 'linear-gradient(135deg,#d6b48a,#a07a4a)' },
    lang: 'uz',
    online: true,
    needsHuman: false,
    aiOn: true,
    unread: 1,
    lastTime: '15 min',
    lastFromMe: false,
    preview: '📸 Photo',
    lastAt: 'May 2025',
    tags: ['Customer'],
    customerSince: 'April 2025',
    location: 'Samarkand',
    summary: 'New customer. 8 messages. Interested in wholesale',
    kpis: { orders: 0, ltv: '0', last: 'Today', conv: 'pending' },
    orders: [],
    suggestions: [
      'Salom! Qanday yordamga ehtiyojingiz bor?',
      'Ildiz narxlarini yuboraman',
      'Minimum buyurtma 50 dona',
    ],
  },
  {
    id: 'whatsapp::biz1::whatsapp::cust4',
    name: 'Mohamed Hassan',
    handle: '+998911234567',
    platform: 'whatsapp',
    avatar: { initials: 'MH', color: 'linear-gradient(135deg,#d97b8a,#9b3f5a)' },
    lang: 'uz',
    online: false,
    needsHuman: false,
    aiOn: true,
    unread: 0,
    lastTime: 'yesterday',
    lastFromMe: false,
    preview: 'Delivery status?',
    lastAt: 'May 2025',
    tags: ['Customer'],
    customerSince: 'February 2025',
    location: 'Dubai',
    summary: 'International customer. 34 messages. Regular orders',
    kpis: { orders: 5, ltv: '650', last: '1 week', conv: '+8%' },
    orders: [
      { t: 'Export shipment', s: 'In transit', price: '$320' },
    ],
    suggestions: [
      'Your order is on the way',
      'Tracking number: TRK123456',
      'Expected delivery Friday',
    ],
  },
  {
    id: 'instagram::biz1::dm::cust5',
    name: 'Gulnora Zakaeva',
    handle: '@gulnora.designs',
    platform: 'instagram',
    avatar: { initials: 'GZ', color: 'linear-gradient(135deg,#a8b899,#5d7548)' },
    lang: 'uz',
    online: true,
    needsHuman: true,
    aiOn: false,
    unread: 2,
    lastTime: '8 min',
    lastFromMe: false,
    preview: 'Custom design request',
    lastAt: 'May 2025',
    tags: ['Needs Human', 'VIP'],
    customerSince: 'May 2025',
    location: 'Tashkent',
    summary: 'Designer client. 5 messages. Complex custom order',
    kpis: { orders: 0, ltv: '0', last: 'Today', conv: '—' },
    orders: [],
    suggestions: [
      'Design review available',
      'Revision cycle starts tomorrow',
      'Need timeline confirmation',
    ],
  },
];
